#ifndef _H_IRISVIRTUALCODENUMBER_
#define _H_IRISVIRTUALCODENUMBER_

#define PUSH_ENV	0
#define POP_ENV		1
#define PUSH		2
#define POP			3
#define CRE_ENV		4
#define LOAD		5
#define	NOL_CALL	6
#define ASSIGN		7
#define HID_CALL	8
#define	SET_FLD		9
#define CLR_FLD		10
#define	FLD_LOAD	11
#define	LOAD_NIL	12
#define	LOAD_TRUE	13
#define	LOAD_FALSE	14
#define	LOAD_SELF	15
#define	IMTH_DEF	16
#define	CMTH_DEF	17
#define	BLK_DEF		18
#define	END_DEF		19
#define	JFON		20
#define	JMP			21
#define	INI_TM		22
#define	INI_CNT		23
#define	CMP_TAC		24
#define	INC_CNT		25
#define	ASSIGN_LOG	26
#define	BRK			27
#define	PUSH_DEEP	28
#define	POP_DEEP	29
#define	RTN			30
#define	CTN			31
#define	ASSIGN_VSL	32
#define	ASSIGN_ITER	33
#define	LOAD_ITER	34
#define	JT			35
#define	ASSIGN_CMP	36
#define	CMP_CMP		37
#define	CRE_CENV	38
#define	DEF_CLS		39
#define	ADD_EXT		40
#define	ADD_MLD		41
#define	ADD_INF		42
#define	PUSH_CNT	43
#define	PUSH_TIM	44
#define	POP_CNT		45
#define	POP_TIM		46
#define	PUSH_UNIM	47
#define	POP_UNIM	48
#define	PUSH_VSL	49
#define	POP_VSL		50
#define	PUSH_ITER	51
#define	POP_ITER	52
#define	STR_DEF		53
#define	GTR_DEF		54
#define	GSTR_DEF	55
#define	SET_AUTH	56
#define	DEF_MLD		57
#define	DEF_INF		58
#define	DEF_INFS	59
#define	CBLK_DEF	60
#define	BLK			61
#define	REG_IRP		62
#define	UREG_IRP	63
#define	ASSIGN_IR	64
#define	GRN			65
#define	SPR			66
#define	LOAD_CAST	67

#endif
