[package]
name = "iris-vm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
iris-lexer = { path = "../iris-lexer" }
iris-parser = { path = "../iris-parser" }
iris-abi = { path = "../iris-abi" }
iris-runtime = { path = "../iris-runtime" }
iris-syntax = { path = "../iris-syntax" }
regex = "1"
icu_casemap = "2"
unicode-normalization = "0.1"
unicode-segmentation = "1.13"
